services:
  - type: web
    name: twilio-doorverbinden-ruth
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    branch: main
    healthCheckPath: "/doorverbinden"
